### ISSUE TITLE
Website returns different results than the endpoint

### ISSUE THREAD

**Issue by Leisvan** [YenFu1/sc2ladder#96]
Hi.
This is my problem: Using the endpoint to retrieve info for some users (for example: Blue#19551, Silver#15946) i get tons of results but non matches the battle tag I provide. However, if I use the same battle tags on the website the results are accurate.

Examples:
Run this command `curl -G "https://www.sc2ladder.com/api/player?query=Blue#19551&limit=200"` and you won't get any account with 'Blue#19551' as a battle tag. Use that same tag in https://www.sc2ladder.com/ and you'll get the right result.

I'll be more than happy if I hear from you guys, I can't provide a pleasant experience to my custom clan ranking due to this issue.
Thanks in advance and keep up the amazing work you're doing with this.

**Comment by jteague9** [comment]
@Leisvan 
url encode the # in the request params
`curl -G "https://www.sc2ladder.com/api/player?query=Blue%2319551&limit=200"` and it works

**Comment by Leisvan** [comment]
Oh man! I feel dumb 😁
Thanks @jteague9 thanks a lot!
